import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import Hero from "./components/heroSection";
import PlotDetails from "./components/plotDetails";
import LocationHighlights from "./components/locationHighlights";
import YacharamProject from "./components/locationHighlights";
import ProjectHighlights from "./components/projectHighlights";
import ContactSection from "./components/contactSection";
import Footer from "./components/footer";
import ProjectGallery from "./components/Galary";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Saanvika Properties | Future city mango garden",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        {children}
        <Hero />
        <PlotDetails />
        
        <ProjectHighlights />
        <LocationHighlights />
        <ProjectGallery />
        <ContactSection />

        <Footer />
      </body>
    </html>
  );
}
